# Generated by Django 4.2.7 on 2023-11-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descricao'),
        ),
    ]
